name: Docker test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test-gameserver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
            cd server
            docker build . --file Dockerfile
            
  test-backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
            cd backup
            docker build . --file Dockerfile
            
            
